# Generated by Django 5.1.6 on 2025-02-27 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_healthgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 2, 27, 14, 22, 21, 933380, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
